### ISSUE TITLE
error

### ISSUE THREAD

**Issue by RajeshAudhurthi** [W3NDO/Organize#1]
unable to move .mp4 to video_files folder

getting this error
mv: unknown option --
Try 'mv --help' for more information.

**Comment by W3NDO** [comment]
If you write mv --help, what do you get

What system are you running?

**Comment by RajeshAudhurthi** [comment]
mv --help shows default commands nothing much.

Size of mp4 files is an issue may be ..?

**Comment by W3NDO** [comment]
Don't think so. Could you show me the exact command you typed?

**Comment by RajeshAudhurthi** [comment]
Okay got it ..that issue was limited to one folder only..other than that particular folder its working fine..tq
